services:
  db:
    image: postgres:17
    container_name: db
    environment:
      POSTGRES_USER: mm
      POSTGRES_PASSWORD: mm
      POSTGRES_DB: mediameta
    ports: ["5434:5432"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mm -d mediameta"]
      interval: 2s
      timeout: 2s
      retries: 20

